[tools]
fzf = "latest"
starship = "latest"
zoxide = "latest"
neovim = "latest"
bat = "latest"
ripgrep = "latest"
fd = "latest"
jq = "latest"
lazygit = "latest"
gh = "latest"
delta = "latest"
yazi = "latest"
gdu = "latest"
btop = "latest"
rclone = "latest"
uv = "latest"
difftastic = "latest"
